### ISSUE TITLE
Webview not Launching?

### ISSUE THREAD

**Issue by Bambalow28** [e-oj/visa#3]
So I tried using this library but everytime I try to connect it to my button it doesnt launch. I put it inside a function with async and button click it should call that function.

**Comment by rafarvns** [comment]
> 
> 
> So I tried using this library but everytime I try to connect it to my button it doesnt launch. I put it inside a function with async and button click it should call that function.

Try like that 

`  @override
  Widget build(BuildContext context) {
    var googleAuth = GoogleAuth();
    var visa = googleAuth.visa;
    return Scaffold(
      body: visa.authenticate(
        clientID: 'xxx',
        redirectUri: 'xxx',
        state: 'xxx',
        scope: 'xxx',
        onDone: (AuthData authData) {
          print(authData);
          Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => HomePage()));
        }
      ),
    );
  }`

**Comment by Bambalow28** [comment]
Hmm could u help? I tried it but still having trouble executing it

**Comment by Bambalow28** [comment]
Im trying it but it still not popping up

**Comment by rafarvns** [comment]
paste here your code, i'll try help you

**Comment by Bambalow28** [comment]
So I had it in a function like this right, 

launchURL() async {
  DiscordAuth discordAuth = DiscordAuth();
  var visa = discordAuth.visa;

  return visa.authenticate(
      clientID: clientID,
      redirectUri: redUrl,
      scope: 'identify,email,guilds,guilds.join',
      state: 'discordAuth',
      onDone: done);
}

done(AuthData authData) {
  print(authData);
}

then in my main I triggered it like this,

onTap: () => {
                        checkPressed
                            ? Colors.white
                            : const Color.fromRGBO(18, 18, 18, 1.0),
                        setState(() {
                          checkPressed = !checkPressed;
                          launchURL();
                        })
                      },

**Comment by Bambalow28** [comment]
Oh I got it working! But now its not printing the AuthData lol

**Comment by rafarvns** [comment]
visa.authenticate return a Widget, then do you need put in a body or a child.
like:
return Container(
    child: launchURL();
)

**Comment by rafarvns** [comment]
> 
> 
> Oh I got it working! But now its not printing the AuthData lol

cool, you can try verify the scope... search in discord api doc, or try this https://github.com/e-oj/visa/blob/master/test_app/lib/auth-page.dart

**Comment by Bambalow28** [comment]
Hmm so my problem now is it doesnt seem to do the callback function after it finishes. After being redirected it just doesnt do anything else.

**Comment by Bambalow28** [comment]
So I revised my code to this,

```dart
void navigateToHome() {
    Navigator.pushAndRemoveUntil(
        context,
        MaterialPageRoute(builder: (context) => HomePage()),
        ModalRoute.withName("/LoginPage"));
  }

  launchURL(BuildContext context) {
    var done = (AuthData authData) {
      print('test');
      // print(authData.accessToken);
      navigateToHome();
    };

    return DiscordAuth().visa.authenticate(
        clientID: clientID,
        redirectUri: redUrl,
        scope: 'identify',
        state: 'discordAuth',
        onDone: done);
  }
```

but after login it redirects to me to my sample 'google.ca' but doesnt print me anything or push to another page.

**Comment by Bambalow28** [comment]
Hey so yeah I cant get the callback to work.

**Comment by rafarvns** [comment]
do you need send the correct scope, or modify the source for accept only "identify" scope.

as shown in the example I mentioned earlier  => https://github.com/e-oj/visa/blob/master/test_app/lib/auth-page.dart
the correct scope is: "identify email"

**Comment by Bambalow28** [comment]
So I have tried changing it to that but it never loaded. Its just a blank white screen

**Comment by rafarvns** [comment]
your console shows any error message?

**Comment by Bambalow28** [comment]
Nah. Not showing or displaying anything

**Comment by Bambalow28** [comment]
If I only have one scope then it works (like it shows the discord login) but still after that it still doesnt call the callback function

**Comment by rafarvns** [comment]
do you know use the debug tool? try use
or can you send your code? 
i'll try execute here

**Comment by Bambalow28** [comment]
Not really. But here is my code.

**Comment by Bambalow28** [comment]
//Login Widget
class LoginPage extends StatefulWidget {
  LoginPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _LoginState createState() => _LoginState();
}

//Login Page Widget State
class _LoginState extends State<LoginPage> with SingleTickerProviderStateMixin {
  TextStyle style = TextStyle(fontFamily: 'Montserrat', fontSize: 20.0);
  bool isLoggedIn = false;
  bool checkPressed = false;

  navigateToHome() {
    Navigator.pushAndRemoveUntil(
        context,
        MaterialPageRoute(builder: (context) => HomePage()),
        ModalRoute.withName("/LoginPage"));
  }

  launchURL() {
    done(AuthData authData) {
      print('test');
      // print(authData.accessToken);
      // navigateToHome();
    }

    return Scaffold(
        appBar: AppBar(
          title: Text(
            'Discord Login',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
          backgroundColor: const Color.fromRGBO(38, 38, 38, 1.0),
          leading: IconButton(
              icon: Icon(Icons.arrow_back_ios_rounded, size: 25.0),
              onPressed: () => Navigator.pop(context)),
        ),
        body: DiscordAuth().visa.authenticate(
            clientID: clientID,
            clientSecret: clientSecret,
            redirectUri: redirectURL,
            state: 'discordAuth',
            scope: 'identify',
            onDone: done));
  }

  @override
  Widget build(BuildContext context) {
    //Login View
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: <Widget>[
            WaveWidget(
              config: CustomConfig(
                gradients: [
                  [Colors.cyanAccent, Color(0x66FF9800)],
                  [Colors.cyan, Color(0x55FFEB3B)]
                ],
                durations: [10800, 6000],
                heightPercentages: [0.50, 0.52],
                blur: MaskFilter.blur(BlurStyle.solid, 10),
                gradientBegin: Alignment.bottomLeft,
                gradientEnd: Alignment.topRight,
              ),
              waveAmplitude: 0,
              backgroundColor: Color.fromRGBO(18, 18, 18, 1),
              size: Size(
                double.infinity,
                double.infinity,
              ),
            ),
            Container(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
              color: Colors.transparent,
              child: Padding(
                padding: const EdgeInsets.only(
                    left: 40.0, right: 40.0, bottom: 20.0, top: 190.0),
                child: Column(
                  children: <Widget>[
                    //Logo Photo PNG
                    Expanded(
                      child: Container(
                        child: Image.asset(
                          "assets/images/newElixirLogo.png",
                          fit: BoxFit.contain,
                          width: 150.0,
                        ),
                      ),
                    ),
                    // Padding(padding: const EdgeInsets.all(100.0)),
                    Expanded(
                      child: SizedBox(),
                    ),
                    GestureDetector(
                      onTap: () => {
                        checkPressed
                            ? Colors.white
                            : const Color.fromRGBO(18, 18, 18, 1.0),
                        setState(() {
                          checkPressed = !checkPressed;
                          // navigateToHome();
                          Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => launchURL()));
                        })
                      },
                      child: Container(
                        decoration: BoxDecoration(
                            color: const Color.fromRGBO(23, 23, 23, 1.0),
                            borderRadius:
                                BorderRadius.all(Radius.circular(30.0)),
                            boxShadow: [
                              BoxShadow(
                                  color: Colors.grey[900].withOpacity(0.5),
                                  spreadRadius: 3,
                                  blurRadius: 2,
                                  offset: Offset(0, 3)),
                            ]),
                        child: Container(
                          width: MediaQuery.of(context).size.width,
                          padding: EdgeInsets.fromLTRB(20.0, 15.0, 20.0, 15.0),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: <Widget>[
                              Icon(
                                CustomIcons.discord,
                                color: Colors.white,
                              ),
                              Padding(
                                padding: EdgeInsets.only(right: 10.0),
                              ),
                              Text("Login via Discord",
                                  textAlign: TextAlign.center,
                                  style: style.copyWith(
                                      color: Colors.white,
                                      fontWeight: FontWeight.bold)),
                            ],
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 130.0,
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by Bambalow28** [comment]
Not all the code privacy purposes but yeah like this.

**Comment by rafarvns** [comment]
> 
> 
> Not all the code privacy purposes but yeah like this.

can you use https://pastebin.com for send your code?
anyway, im at work now, when i go to my home, will check ok?

**Comment by Bambalow28** [comment]
yup no problem

**Comment by Bambalow28** [comment]
https://pastebin.com/db66RdAi
Let me know when u are available so I can make it public

**Comment by e-oj** [comment]
@Bambalow28 Make it public. I'll have a look.

**Comment by e-oj** [comment]
@rafarvns Thanks for stepping in and helping him out as well.

**Comment by e-oj** [comment]
@Bambalow28 the authenticate function returns a webview component. I'd advise you to use it as a separate page in your app for simplicity. I'd like to see where launchUrl gets called in your code (below)

```dart
void navigateToHome() {
  Navigator.pushAndRemoveUntil(
      context,
      MaterialPageRoute(builder: (context) => HomePage()),
      ModalRoute.withName("/LoginPage"));
}

launchURL(BuildContext context) {
  var done = (AuthData authData) {
    print('test');
    // print(authData.accessToken);
    navigateToHome();
  };

  return DiscordAuth().visa.authenticate(
      clientID: clientID,
      redirectUri: redUrl,
      scope: 'identify',
      state: 'discordAuth',
      onDone: done);
}
```

**Comment by Bambalow28** [comment]
So its now public. Please see link

**Comment by Bambalow28** [comment]
So should I try creating a separate page for it?

**Comment by e-oj** [comment]
@Bambalow28 the issue might be your redirect url. You have 

```dart
String redirectURL =
    'https://discord.com/api/oauth2/authorize?client_id=799140079494496276&redirect_uri=https%3A%2F%2Fwww.google.ca&response_type=code&scope=identify%20guilds%20guilds.join%20email'
```
The redirect url is the page you want to end up on after authentication. More importantly, the oauth service will pass the authentication results through this url. The truth is, we'll never actually load the page. We simply intercept before the url loads and get the returned data by parsing the url. Try this instead:

```dart
String redirectURL = 'https://www.blah.com';
```
Let me know if that works.

**Comment by e-oj** [comment]
Add screenshots of what you're seeing on the app as well. I just tried adding that redirect url to my discord portal and it gets cut off because it's too long.  [Discord oauth portal](https://drive.google.com/file/d/1sxoFTRUpULFTZKPSagvKDPbDu0XwbXen/view?usp=sharing), [App view](https://drive.google.com/file/d/1W5Z22WWMCWhuM_eu3ZGMCsOQL9aMDDUG/view?usp=sharing)

**Comment by e-oj** [comment]
@Bambalow28 Even after changing the redirecturl in the code to match the truncated url in the discord portal, I get an [invalid redirect uri error](https://drive.google.com/file/d/1DWSi4Ta1eEs2mDJQgim_NXhFL_nlB-gw/view?usp=sharing)

**Comment by e-oj** [comment]
I'll definitely need screenshots of your app for this one

**Comment by Bambalow28** [comment]
Hmm okay ill check it out. Ill send screenshots

**Comment by Bambalow28** [comment]
Wait but isnt that the redirect url thts needed since im using discord?

**Comment by Bambalow28** [comment]
Oh! Just a quick add. Ur scope had "identify email"? I couldnt make that run for mine.

**Comment by Bambalow28** [comment]
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 21 14 34](https://user-images.githubusercontent.com/34558155/113369555-9ce60b80-932f-11eb-868a-b99f2c06a727.png)

**Comment by Bambalow28** [comment]
^^ Result I get with "identify email"

**Comment by Bambalow28** [comment]
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 21 15 19](https://user-images.githubusercontent.com/34558155/113369598-b1c29f00-932f-11eb-8331-30ef24b90aa4.png)

**Comment by Bambalow28** [comment]
^^ Result I get with just "identify"

**Comment by e-oj** [comment]
What happens after you select "Authorize"?

**Comment by Bambalow28** [comment]
Redirects to the endpoint I had it in which is google but never triggers the callback or print anything

**Comment by e-oj** [comment]
send a screenshot.

**Comment by Bambalow28** [comment]
![Screen Shot 2021-04-01 at 9 35 02 PM](https://user-images.githubusercontent.com/34558155/113370552-2696d880-9332-11eb-8d56-69eb0a7f10e5.png)

**Comment by Bambalow28** [comment]
Thts exactly what I see

**Comment by e-oj** [comment]
> Wait but isnt that the redirect url thts needed since im using discord?

No. There's no required url. The redirect url should be a link to a page on your website. In this case, it's an app, so we intercept the url, extract the oauth data and pass it to the app through the callback.

**Comment by e-oj** [comment]
> Thts exactly what I see

Your redirect url in this case is google.com?

**Comment by Bambalow28** [comment]
> > Wait but isnt that the redirect url thts needed since im using discord?
> 
> No. There's no required url. The redirect url should be a link to a page on your website. In this case, it's an app, so we intercept the url, extract the oauth data and pass it to the app through the callback.

Ahh okay I gotcha. Hmm so I wonder what is happening.

**Comment by Bambalow28** [comment]
> > Thts exactly what I see
> 
> Your redirect url in this case is google.com?

yes. well "/www.google.ca"

**Comment by e-oj** [comment]
And that matches the redirect url in your discord portal?

**Comment by Bambalow28** [comment]
Yes it does

**Comment by e-oj** [comment]
Try this. I want to see if we're getting any oauth data back in the first place.

```dart
final OAuth oAuth = OAuth(
        baseUrl: baseUrl,
        clientID: clientID,
        redirectUri: redirectUri,
        state: state,
        scope: scope,
        clientSecret: clientSecret);

return oAuth.authenticate(
    clearCache: false,
    onDone: (Map<String, String> responseData) {
       print(responseData)
    });
```

**Comment by Bambalow28** [comment]
I did it. Nothing still.

**Comment by Bambalow28** [comment]
baseURL is the google url in my case right? and state is whichever?

**Comment by e-oj** [comment]
Sorry, forgot to mention. Baseurl in your case is the base discord oauth url: https://discord.com/api/oauth2/authorize

**Comment by Bambalow28** [comment]
> Sorry, forgot to mention. Baseurl in your case is the base discord oauth url: https://discord.com/api/oauth2/authorize

Okay sorry for late reply but yeah still nothing

**Comment by e-oj** [comment]
This is the code that makes the navigation decision internally. It's possible that the browser is attaching the protocol to the redirect url, causing a mismatch. for instance, if you might have ```redirectUrl = www.google.com``` and the browser makes it ```https://www.google.com```. Is the protocol (http or https) part of your redirect url in the dev portal and in the code?

```dart
navigationDelegate: (NavigationRequest request){
          String url = request.url;
          
          /// Intercepts request if current url
          /// starts with redirect url
          if (url.startsWith(redirectUri)) {
            var returnedData = _getQueryParams(url);
            returnedData[CLIENT_ID_KEY] = clientID;
            returnedData[REDIRECT_URI_KEY] = redirectUri;
            returnedData[STATE_KEY] = state;

            if (clientSecret != null) {
              returnedData[CLIENT_SECRET_KEY] = clientSecret;
            }

            onDone(returnedData);
          }

          return NavigationDecision.navigate;
        });
```

**Comment by Bambalow28** [comment]
> This is the code that makes the navigation decision internally. It's possible that the browser is attaching the protocol to the redirect url, causing a mismatch. for instance, if you might have `redirectUrl = www.google.com` and the browser makes it `https://www.google.com`. Is the protocol (http or https) part of your redirect url in the dev portal?
> 
> ```dart
> navigationDelegate: (NavigationRequest request){
>           String url = request.url;
>           
>           /// Intercepts request if current url
>           /// starts with redirect url
>           if (url.startsWith(redirectUri)) {
>             var returnedData = _getQueryParams(url);
>             returnedData[CLIENT_ID_KEY] = clientID;
>             returnedData[REDIRECT_URI_KEY] = redirectUri;
>             returnedData[STATE_KEY] = state;
> 
>             if (clientSecret != null) {
>               returnedData[CLIENT_SECRET_KEY] = clientSecret;
>             }
> 
>             onDone(returnedData);
>           }
> 
>           return NavigationDecision.navigate;
>         });
> ```

Hmm I wonder but yes it is part of my redirect url in the dev portal.

**Comment by Bambalow28** [comment]
Even if I try with another url it doesnt work

**Comment by e-oj** [comment]
in the code do you have it as https://www.google.ca? this is a strange one really

**Comment by Bambalow28** [comment]
> in the code do you have it as https://www.google.com? this is a strange one really

I have it as https://www.google.ca

**Comment by e-oj** [comment]
Seems like the comparison in the if statement is returning ```false``` for some reason. I'll push a 'debug mode' update tomorrow so we can get some logs as the code runs. That will help us pinpoint the issue. Thanks for bringing this to my attention.

**Comment by Bambalow28** [comment]
> Seems like the comparison in the if statement is returning `false` for some reason. I'll push a 'debug mode' update tomorrow so we can get some logs as the code runs. That will help us pinpoint the issue. Thanks for bringing this to my attention.

Okay great thanks man! Sorry if it was kind of a hassle. I was just trying to get oauth2 running in flutter and ur library seemed the perfect and not as hard one to implement

**Comment by e-oj** [comment]
Yeah, no worries brother. The whole thing is mean to be super easy. We'll get to the bottom of this.

**Comment by e-oj** [comment]
@Bambalow28 Update to v1.0.4 and do this:
```dart
var discordAuth = DiscordAuth();
discordAuth.debug = true;

// everything else stays the same.
```

You'll get debug logs that should help us find the error. Let me know how it goes.

**Comment by Bambalow28** [comment]
Alright thanks! Will try to do it tonight

Sent By Joshua Alanis

**Comment by Bambalow28** [comment]
Hey bro I got it. Got the logs. 'Redirect Url Not Found'. Ill send pastebin.

**Comment by Bambalow28** [comment]
https://pastebin.com/mtshUsq7

**Comment by Bambalow28** [comment]
Here is after clicking authorize. https://pastebin.com/f6Yms0U5

**Comment by e-oj** [comment]
Well, that's the issue right there:
```
flutter: --VISA-DEBUG: In OAuth -> Url = https://www.google.ca/#token_type=Bearer&access_token=we3Rsph7pQWOylscX6Y2Ims1rBdx8Y&expires_in=604800&scope=identify&state=dicordAuth
flutter: --VISA-DEBUG: In OAuth -> Redirect Url = https://discord.com/api/oauth2/authorize?client_id=799140079494496276&redirect_uri=https%3A%2F%2Fwww.google.ca&response_type=code&scope=identify%20email%20guilds%20guilds.join
```
The redirect url in your discord dev portal is
``` 
https://www.google.ca/
```
but the redirect url you're passing to authenticate (in the code) is:
``` 
https://discord.com/api/oauth2/authorize?client_id=799140079494496276&redirect_uri=https%3A%2F%2Fwww.google.ca&response_type=code&scope=identify%20email%20guilds%20guilds.join
```
You said you changed the code to use ``` https://www.google.ca/``` as the redirect url. Let me see the updated code.

**Comment by Bambalow28** [comment]
Finally it worked!! Thankyou!
