### ISSUE TITLE
Null-safety

### ISSUE THREAD

**Issue by 3eif** [e-oj/visa#4]
Will this library be upgraded to null-safety?

**Comment by 3eif** [comment]
I've made a PR (#5) for null-safety, it has some issues though.

**Comment by e-oj** [comment]
There are no plans to use the null safety features at the moment. I'll tell you right now, you won't run into any null pointer errors in the code. Critical fields are either marked as required or given defaults and nullable fields are checked before they're used. It's not broken, so there's nothing to fix. I'm focused on adding new providers to the library. Cosmetic changes can come later and an upgrade to use Dart's null safety features must be done very carefully.

**Comment by 3eif** [comment]
I am having issues with this package though since it depends on non null-safety versions of other packages such as http.

```
Because no versions of google_fonts match >2.0.0 <3.0.0 and google_fonts 2.0.0 depends on http ^0.13.0, google_fonts ^2.0.0 requires http ^0.13.0.

And because every version of visa depends on http ^0.12.2, google_fonts ^2.0.0 is incompatible with visa.

So, because my_app depends on both visa ^1.0.4 and google_fonts ^2.0.0, version solving failed.
pub get failed (1; So, because my_app depends on both visa ^1.0.4 and google_fonts ^2.0.0, version solving failed.)
exit code 1
```

**Comment by e-oj** [comment]
I won't be accepting your PR right now but I appreciate the effort so I'll show you why you're getting the error. Basically, getAuthData is written to accept a ```Map<String, String>```. When it's called in ```SimpleAuth```, we pass it the result of ```_getQueryParams``` from the ```OAuth``` class which you changed to be a ```Map<String, String?>```. I've added both functions here (from your pr) so you'll see what I mean.

```dart
getAuthData: (Map<String, String> oauthData) async {
    if (debugMode) debug('In FacebookAuth -> OAuth Data: $oauthData');

    final String token = oauthData[OAuth.TOKEN_KEY];
    final String? token = oauthData[OAuth.TOKEN_KEY];
    if (debugMode) debug('In FacebookAuth -> OAuth token: $token');

    // User profile API endpoint.
    var baseProfileUrl = 'https://graph.facebook.com/me';
    final String profileUrl = '$baseProfileUrl'
        '?access_token=$token'
        '&fields=first_name,last_name,email';
    var profileResponse = await http.get(Uri.parse(profileUrl));
    var profileJson = json.decode(profileResponse.body);
    if (debugMode)
      debug('In FacebookAuth -> Returned Profile Json: $profileJson');
    return authData(profileJson, oauthData);
  });
```

```dart
Map<String, String?> _getQueryParams(String url) {
  if (debugMode) debug('In OAuth -> Getting Query Params From Url: $url');

  final List<String> urlParams = url.split(RegExp('[?&# ]'));
  final Map<String, String> queryParams = HashMap();
  final Map<String, String?> queryParams = HashMap();
  List<String> parts;

  for (String param in urlParams) {
    if (!param.contains('=')) continue;
    parts = param.split('=');
    queryParams[parts[0]] = Uri.decodeFull(parts[1]);
  }
  if (debugMode) debug('In OAuth -> Extracted Query Params: $queryParams');
  return queryParams;
}
```

**Comment by e-oj** [comment]
> I am having issues with this package though since it depends on non null-safety versions of other packages such as http.
> 
> ```
> Because no versions of google_fonts match >2.0.0 <3.0.0 and google_fonts 2.0.0 depends on http ^0.13.0, google_fonts ^2.0.0 requires http ^0.13.0.
> 
> And because every version of visa depends on http ^0.12.2, google_fonts ^2.0.0 is incompatible with visa.
> 
> So, because my_app depends on both visa ^1.0.4 and google_fonts ^2.0.0, version solving failed.
> pub get failed (1; So, because my_app depends on both visa ^1.0.4 and google_fonts ^2.0.0, version solving failed.)
> exit code 1
> ```

Seems like I simply need to upgrade the version of http being used .

**Comment by e-oj** [comment]
I'll look into this

**Comment by 3eif** [comment]
> 
> 
> > I am having issues with this package though since it depends on non null-safety versions of other packages such as http.
> > ```
> > Because no versions of google_fonts match >2.0.0 <3.0.0 and google_fonts 2.0.0 depends on http ^0.13.0, google_fonts ^2.0.0 requires http ^0.13.0.
> > 
> > And because every version of visa depends on http ^0.12.2, google_fonts ^2.0.0 is incompatible with visa.
> > 
> > So, because my_app depends on both visa ^1.0.4 and google_fonts ^2.0.0, version solving failed.
> > pub get failed (1; So, because my_app depends on both visa ^1.0.4 and google_fonts ^2.0.0, version solving failed.)
> > exit code 1
> > ```
> 
> Seems like I simply need to upgrade the version of http being used .

I don't think that's possible though because the latest version of http is using null-safety.

**Comment by 3eif** [comment]
> 
> 
> I won't be accepting your PR right now but I appreciate the effort so I'll show you why you're getting the error. Basically, getAuthData is written to accept a `Map<String, String>`. When it's called in `SimpleAuth`, we pass it the result of `_getQueryParams` from the `OAuth` class which you changed to be a `Map<String, String?>`. I've added both functions here (from your pr) so you'll see what I mean.
> 
> ```dart
> getAuthData: (Map<String, String> oauthData) async {
>     if (debugMode) debug('In FacebookAuth -> OAuth Data: $oauthData');
> 
>     final String token = oauthData[OAuth.TOKEN_KEY];
>     final String? token = oauthData[OAuth.TOKEN_KEY];
>     if (debugMode) debug('In FacebookAuth -> OAuth token: $token');
> 
>     // User profile API endpoint.
>     var baseProfileUrl = 'https://graph.facebook.com/me';
>     final String profileUrl = '$baseProfileUrl'
>         '?access_token=$token'
>         '&fields=first_name,last_name,email';
>     var profileResponse = await http.get(Uri.parse(profileUrl));
>     var profileJson = json.decode(profileResponse.body);
>     if (debugMode)
>       debug('In FacebookAuth -> Returned Profile Json: $profileJson');
>     return authData(profileJson, oauthData);
>   });
> ```
> 
> ```dart
> Map<String, String?> _getQueryParams(String url) {
>   if (debugMode) debug('In OAuth -> Getting Query Params From Url: $url');
> 
>   final List<String> urlParams = url.split(RegExp('[?&# ]'));
>   final Map<String, String> queryParams = HashMap();
>   final Map<String, String?> queryParams = HashMap();
>   List<String> parts;
> 
>   for (String param in urlParams) {
>     if (!param.contains('=')) continue;
>     parts = param.split('=');
>     queryParams[parts[0]] = Uri.decodeFull(parts[1]);
>   }
>   if (debugMode) debug('In OAuth -> Extracted Query Params: $queryParams');
>   return queryParams;
> }
> ```

Thanks, I managed to fix the error!

**Comment by e-oj** [comment]
Updating the dependencies fixed this. Thanks for pointing it out!

**Comment by e-oj** [comment]
All dependencies have been updated in the [v2.0.0](https://pub.dev/packages/visa) release
